# MODIFIED 6-proxy-vs-delegate.yaml
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: hello-proxy-vs # Keep the same name to replace the old one
  namespace: istio-chain-example
spec:
  # --- Remove these fields for delegation ---
  # exportTo:
  # - '*'
  # hosts:
  # - hello-proxy-svc.istio-chain-example.svc.cluster.local
  # --- Keep only the http routes ---
  http:
  - name: "redirect-to-actual-backend" # This name might be less relevant now
    route:
    - destination:
        host: hello-svc.istio-chain-example.svc.cluster.local
        port:
          number: 80
      weight: 100
