# 3-proxy-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hello-proxy-svc # The intermediate target service name
  namespace: istio-chain-example
spec:
  # No selector - this service doesn't directly route to pods
  ports:
  - name: http
    port: 80 # Port targeted by the first VS
    targetPort: http-proxy-hello
