apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: intermediate-vs
  namespace: rollout-demo
spec:
  hosts:
  - "intermediate-service.rollout-demo.svc.cluster.local" # Must match Destination
  http:
  - route:
    - destination:
        host: backend-service-v1.rollout-demo.svc.cluster.local
        port:
          number: 80
