apiVersion: v1
kind: ConfigMap
metadata:
  name: user-mocks-configmap
data:
  users.json: |
    {
      "request": {
        "method": "GET",
        "path": "/v1/users"
      },
      "response": {
        "body": [
          { "id": 1, "name": "John" },
          { "id": 2, "name": "Marry" }
        ]
      }
    }

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: user-mocks-configmap-experiment
data:
  users.json: |
    {
      "request": {
        "method": "GET",
        "path": "/v1/users"
      },
      "response": {
        "body": [
          { "id": 1, "name": "John experiment -1" },
          { "id": 2, "name": "Marry experiment" }
        ]
      }
    }
