apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: webui-rollout
spec:
  http:
  - name: primary
    route:
    - destination:
        host: webui-rollout
        port:
          number: 3030
        subset: stable  # referenced in canary.trafficRouting.webui.destinationRule.stableSubsetName
      weight: 100
    - destination:
        host: webui-rollout
        port:
          number: 3030
        subset: canary  # referenced in canary.trafficRouting.webui.destinationRule.canarySubsetName
      weight: 0

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: webui-rollout-delegate
spec:
  gateways:
    - webui-rollout-gateway
  hosts:
    - "*"
  http:
  - match:
      - headers:
          x-node-experiment:
            exact: "true"
    name: experimental
    route:
    - destination:
        host: webui-experimental-rollout
        port:
          number: 3030
        subset: stable  # referenced in canary.trafficRouting.webui.destinationRule.stableSubsetName
      weight: 100
    - destination:
        host: webui-experimental-rollout
        port:
          number: 3030
        subset: canary  # referenced in canary.trafficRouting.webui.destinationRule.canarySubsetName
      weight: 0
  - name: primary
    route:
    - destination:
        host: webui-rollout
        port:
          number: 3030
        subset: stable  # referenced in canary.trafficRouting.webui.destinationRule.stableSubsetName
      weight: 100
    - destination:
        host: webui-rollout
        port:
          number: 3030
        subset: canary  # referenced in canary.trafficRouting.webui.destinationRule.canarySubsetName
      weight: 0
